### PR TITLE
[Fix] GoTLS function offset 

### PR DESCRIPTION
**Pull request by wlingze**

### CODE REVIEW

**Comment by wlingze** [comment]
I have created some test cases for the `docker` arm64 binary file, See wlingze/ecapture#2 for details. 
When i use `IdaPro`, `readelf` or simplely retrieve all symbols from `*elf.File`, it works and I obtain the correct address. 
When I use `*gosym.Table`, the address is incorrect. `address = 0x00635cb0`
Also, when `*gosym.Table` is built, the data contains errors.
> you can set a condition breakpoint in `/usr/lib/go/src/debug/gosym/pclntab.go` at line 308 with i==6626, where the `*gosym.Func` is built.

And I used [go-parser](https://github.com/0xjiayu/go_parser) with IdaPro, which shows that `gopclntab` contains **incorrect data**.

in this address: `data(0x238980) + .textbase(0x3fd1e0) = 0x00635cb0` 
image

> There's another thing: 
> I've previously built some simple binary files for testing, see wlingze/ecapture#1, and they run well after removing the IdaProOffset. 

### So `debug/gosym` get wrong address, because binary file `gopclntable` data wrong or need other calculate.  

>  `debug/gosym` get wrong, but `go-parser` get correct data. 

in `go-parser` use this text-start: 
image
in `debug/gosym` use this text-start: 
image

**Comment by wlingze** [comment]
# why this f.textStart error? 

this f.textStart data from here: 
`/usr/lib/go/src/debug/gosym/pclntab.go:258`
image
and this `t.PC` come from `NewLineTable`, in code `~/ecapture/user/config/config_gotls.go:333`. 

in other side, `go-parser` [get this textStart data from pclntbl table](https://github.com/0xjiayu/go_parser/blob/e90ad706f958cded660901880616107895e2be88/pclntbl.py#L204). 



## rootcause: 
`debug/gosym` use PC passed by call `NewLineTable` for `textStart`. 
But this  `textStart` should get from pclntable. 

The relevant code changed by [go pr 366695](https://go-review.googlesource.com/c/go/+/366695)

## solution: 
1. use symbols from `*elf.File` like nopie case, you can get correct address. (Checked)
2. use symbols get `runtime.text` address, pass to `NewLineTable`, like [go pr 366695](https://go-review.googlesource.com/c/go/+/366695/2/src/cmd/internal/objfile/objfile.go#145) (NoChecked)

**Comment by wlingze** [comment]
this code change by [golang pr 366695](https://go-review.googlesource.com/c/go/+/366695)

**Comment by GTMany** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
MengTL4, @SkyWuZJU, @cryptodylw533, @psych2go, @YixuanFranco, @QSlotus, @Dreamerryao, @C-wjp, @0oBreakDarko0, @DINGYIOK, @vic220309, @starbt, @Mrzouning, @bb7790cc, @gxonex, @lianguooo, @joyc, @555wkg, @altopersei, @CccccJJ, @zhangr4, @lilike, @carpONE, @shediaonaren, @someoneonsmile, @jerry117, @ZhaoJiaXuan-Hub, @sssslei, @dethan3, @ck76, @KyleCK, @cy486, @Pana, @xrea1m, @greyireland, @shanjun085, @fenghaojiang, @jackysense, @perfectDefect, @yanhengliu, @TAWang999, @GeraldNotFound, @0x520x650x78, @toplan, @renaissancelab, @haikuoping, @zack-sys, @p65c, @lerrorgk, @run-ze

**Pull request closed without merging**
